### ISSUE TITLE
Needs a release!

### ISSUE THREAD

**Issue by pdfkungfoo** [HughIsaacs2/DatPart#1]
I need a release! Please do away with my impatience.

----

<sub>(👍's for this Issue mean: *"I love this project!"*)</sub>

**Comment by HughIsaacs2** [comment]
😄
It's coming.

**Comment by HughIsaacs2** [comment]
Delivered!
(Windows only for now)

https://github.com/HughIsaacs2/DatPart/releases/tag/0.0.1
