### ISSUE TITLE
how to start the server?

### ISSUE THREAD

**Issue by serapath** [HughIsaacs2/DatPart#10]
hey, just searched for "dat chrome extension" not expecting to find a match, but stumbled upon this project :-)

**What is the best way to get it work on linux mint?**

I installed the extension, cloned the repo, npm installed all dependencies, but didn't know how to start it.
Is added `"scripts": { "start": "electron ." }` to `package.json` and gave `npm start` a try ...but got:

![](http://imgur.com/tAtkLirl.png)

**Comment by HughIsaacs2** [comment]
Honestly, I've never gotten Linux builds working. I kept running into issues that I'm unfamiliar with.

I'm going to push a new update to the server app for Windows real soon and after that I'm going to fully focus on providing Linux and Mac support (via Travis CI).

**Comment by lacker** [comment]
How do you start the server on Windows? I can't find instructions for that either.

**Comment by HughIsaacs2** [comment]
@lacker sorry about the late reply.

You just open it, once it's open the server should be running (I should add something to the UI to make that more apparent).

From there, something like [http://60c525b5589a5099aa3610a8ee550dcd454c3e118f7ac93b7d41b6b850272330.dat_site/](http://60c525b5589a5099aa3610a8ee550dcd454c3e118f7ac93b7d41b6b850272330.dat_site/) should work.

**Comment by oleometal** [comment]
instruction for that please
![captura de pantalla de 2019-02-15 08-43-03](https://user-images.githubusercontent.com/22758826/52863644-09750080-30fe-11e9-85dd-3324a0e9e2ba.png)

**Comment by HughIsaacs2** [comment]
@oleometal  There currently isn't a Linux version.

For now try the Chrome app https://github.com/HughIsaacs2/DatPart/releases/tag/0.0.20
