### ISSUE TITLE
Launching

### ISSUE THREAD

**Issue by jondashkyle** [HughIsaacs2/DatPart#2]
Hey! This is so solid! Just tried installing it via “load unpacked extension”. Goes smoothly. When visiting a dat:// url however a grey page appears containing “Error.” Probably a slip up on my part! Very into this.

**Comment by HughIsaacs2** [comment]
You have to run the second folder as an Electron app (I really should have the Error pages say this).

Sadly the Chrome extension APIs alone aren't enough to download and display Dat sites.

I could have those Error pages load Dats over WebRTC in the future, but it'd be a lesser experience (I think I might do it anyways as a fallback just incase).

**Comment by jondashkyle** [comment]
Oh that makes sense! Hmm… it could be really nice to have a menubar item, either as part of Dat Desktop or a standalone app. Similar to how Dropbox or Now looks. Having it out of the way lends it to being persistently open, which could make this less of an ask of the user.

**Comment by HughIsaacs2** [comment]
Yeah, I coded menubar support in v0.0.1 but didn't let it disappear into the menubar as I needed it to be visible for testing purposes, going to add persistence in the next update.

**Comment by HughIsaacs2** [comment]
https://github.com/HughIsaacs2/DatPart/releases/tag/0.0.5

Tray version delivered!
